apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: productdb
  DB_USER: postgres
  NODE_ENV: production
  PORT: "3000"