apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
  namespace: default
  labels:
    app: product-service
type: Opaque
data:
  DB_PASSWORD: cG9zdGdyZXM=  # base64 encoded "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
  labels:
    app: postgresql
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # base64 encoded "postgres"
  POSTGRES_USER: cG9zdGdyZXM=      # base64 encoded "postgres"
  POSTGRES_DB: cHJvZHVjdHM=        # base64 encoded "products"